[package]
name = "apogee-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
apogee-common = { workspace = true }
nalgebra = { workspace = true }
hifitime = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }
flate2 = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking"] }
regex = "1.10"
urlencoding = "2.1"
hwm14-sys = { path = "../hwm14-sys", optional = true }

[features]
default = []
hwm14 = ["dep:hwm14-sys"]

[[example]]
name = "hwm14_samples"
required-features = ["hwm14"]

[dev-dependencies]
approx = "0.5"
hwm14-sys = { path = "../hwm14-sys" }
ntest = { workspace = true }
