[package]
name = "apogee-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
apogee-common = { workspace = true }
nalgebra = { workspace = true }
hifitime = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }
flate2 = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking"] }

[dev-dependencies]
approx = "0.5"